nav:
  - Home: index.md
  - Application: app.md
  - Architecture: architecture.md
  - User Guide: user-guide.md
  - Loading Data: loading.md
  - Fetching and Scraping: fetching-scraping.md
  - Generation: generation.md
  - Data Management: data-management.md
  - Outputs: outputs.md
  - Development: development.md
  - API Reference:
      - Overview: api/index.md
      - Core: api/core.md
      - Data: api/data.md
      - Fetchers: api/fetchers.md
      - Generators: api/generators.md
      - Loaders: api/loaders.md
      - Models: api/models.md
      - Scrapers: api/scrapers.md
      - Writers: api/writers.md